"""Civ6Ai build priorities: the categories the model can switch on for an AI seat.

Each category becomes three engine AI strategies (light, strong, all-in) in
Data/Civ6Ai_Priorities.sql, generated by scripts/gen_priorities.py. A strategy
is active when the synced game property CIV6AI_PRIO_<player>_<id> equals its
level; the engine asks gameplay Lua (GameEvents.Civ6AiPrio_<id>_<level>) before
each player's turn. When active, the strategy re-weights the engine AI's own
scoring (the same tables Infixo's Real Strategy uses), so the engine still picks
the concrete unit, building and city for the current era.

Weights are percentage adjustments to the engine's base values, the same scale
Real Strategy uses (-100 removes a value, +100 doubles it). Level 2 doubles the
light weights and level 3 multiplies them by four; negatives never go below
-100. District weights are favoured-item values.

The ids are part of the save format (game properties), so never renumber them.
"""
from __future__ import annotations

LEVELS = {1: "light", 2: "strong", 3: "all_in"}
LEVEL_MULT = {1: 1, 2: 2, 3: 4}
LEVEL_BY_NAME = {v: k for k, v in LEVELS.items()}

# Groups: the model picks one posture and up to MAX_FOCUS other categories.
MAX_FOCUS = 3

MIL_NEG_INFRA = {  # what war cuts back
    "PSEUDOYIELD_UNIT_ARCHAEOLOGIST": -50,
    "PSEUDOYIELD_TOURISM": -30,
}

# id, key, group, short description for the prompt, weights.
# Weight dicts: Yields (YIELD_*), PseudoYields (PSEUDOYIELD_*),
# UnitPromotionClasses (PROMOTION_CLASS_*), Districts (DISTRICT_*).
CATEGORIES: list[dict] = [
    # ---- posture ---------------------------------------------------------
    dict(id=1, key="peace", group="posture",
         desc="build up cities: districts, improvements, wonders, settlers; smaller army",
         yields={"YIELD_FOOD": 10, "YIELD_CULTURE": 5, "YIELD_FAITH": 5},
         pseudo={"PSEUDOYIELD_DISTRICT": 20, "PSEUDOYIELD_IMPROVEMENT": 15, "PSEUDOYIELD_WONDER": 15,
                 "PSEUDOYIELD_UNIT_SETTLER": 15, "PSEUDOYIELD_STANDING_ARMY_NUMBER": -15,
                 "PSEUDOYIELD_STANDING_ARMY_VALUE": -15, "PSEUDOYIELD_UNIT_COMBAT": -20,
                 "PSEUDOYIELD_UNIT_NAVAL_COMBAT": -20}),
    dict(id=2, key="war", group="posture",
         desc="more land military units and production, fewer wonders and districts",
         yields={"YIELD_PRODUCTION": 15, "YIELD_GOLD": 10, "YIELD_CULTURE": -10, "YIELD_FAITH": -10},
         pseudo={"PSEUDOYIELD_UNIT_COMBAT": 50, "PSEUDOYIELD_STANDING_ARMY_NUMBER": 20,
                 "PSEUDOYIELD_STANDING_ARMY_VALUE": 20, "PSEUDOYIELD_GPP_GENERAL": 25,
                 "PSEUDOYIELD_DISTRICT": -25, "PSEUDOYIELD_WONDER": -30, "PSEUDOYIELD_IMPROVEMENT": -15,
                 "PSEUDOYIELD_UNIT_SETTLER": -20, **MIL_NEG_INFRA},
         classes={"PROMOTION_CLASS_SIEGE": 15},
         districts={"DISTRICT_ENCAMPMENT": 50}),
    dict(id=3, key="total_war", group="posture",
         desc="almost only land military units; districts, wonders, settlers and culture cut hard",
         yields={"YIELD_PRODUCTION": 30, "YIELD_GOLD": 20, "YIELD_SCIENCE": -20,
                 "YIELD_CULTURE": -30, "YIELD_FAITH": -30},
         pseudo={"PSEUDOYIELD_UNIT_COMBAT": 200, "PSEUDOYIELD_STANDING_ARMY_NUMBER": 50,
                 "PSEUDOYIELD_STANDING_ARMY_VALUE": 50, "PSEUDOYIELD_GPP_GENERAL": 50,
                 "PSEUDOYIELD_DISTRICT": -90, "PSEUDOYIELD_WONDER": -100, "PSEUDOYIELD_IMPROVEMENT": -60,
                 "PSEUDOYIELD_UNIT_SETTLER": -80, "PSEUDOYIELD_UNIT_ARCHAEOLOGIST": -100,
                 "PSEUDOYIELD_UNIT_RELIGIOUS": -80, "PSEUDOYIELD_UNIT_TRADE": -60,
                 "PSEUDOYIELD_TOURISM": -100, "PSEUDOYIELD_SPACE_RACE": -80, "PSEUDOYIELD_HAPPINESS": -50,
                 "PSEUDOYIELD_UNIT_NAVAL_COMBAT": -25},
         classes={"PROMOTION_CLASS_SIEGE": 25},
         districts={"DISTRICT_ENCAMPMENT": 100}),
    dict(id=4, key="naval_war", group="posture",
         desc="more warships and harbours, fewer wonders and districts",
         yields={"YIELD_PRODUCTION": 15, "YIELD_GOLD": 10, "YIELD_CULTURE": -10, "YIELD_FAITH": -10},
         pseudo={"PSEUDOYIELD_UNIT_NAVAL_COMBAT": 60, "PSEUDOYIELD_STANDING_ARMY_NUMBER": 20,
                 "PSEUDOYIELD_STANDING_ARMY_VALUE": 20, "PSEUDOYIELD_GPP_ADMIRAL": 30,
                 "PSEUDOYIELD_DISTRICT": -25, "PSEUDOYIELD_WONDER": -30, "PSEUDOYIELD_IMPROVEMENT": -15,
                 "PSEUDOYIELD_UNIT_SETTLER": -20, **MIL_NEG_INFRA},
         classes={"PROMOTION_CLASS_NAVAL_MELEE": 15, "PROMOTION_CLASS_NAVAL_RANGED": 15,
                  "PROMOTION_CLASS_NAVAL_RAIDER": 10},
         districts={"DISTRICT_HARBOR": 60}),
    dict(id=5, key="naval_total_war", group="posture",
         desc="almost only warships; land army, districts, wonders and culture cut hard",
         yields={"YIELD_PRODUCTION": 30, "YIELD_GOLD": 20, "YIELD_SCIENCE": -20,
                 "YIELD_CULTURE": -30, "YIELD_FAITH": -30},
         pseudo={"PSEUDOYIELD_UNIT_NAVAL_COMBAT": 220, "PSEUDOYIELD_STANDING_ARMY_NUMBER": 50,
                 "PSEUDOYIELD_STANDING_ARMY_VALUE": 50, "PSEUDOYIELD_GPP_ADMIRAL": 50,
                 "PSEUDOYIELD_UNIT_COMBAT": -40,
                 "PSEUDOYIELD_DISTRICT": -90, "PSEUDOYIELD_WONDER": -100, "PSEUDOYIELD_IMPROVEMENT": -60,
                 "PSEUDOYIELD_UNIT_SETTLER": -80, "PSEUDOYIELD_UNIT_ARCHAEOLOGIST": -100,
                 "PSEUDOYIELD_UNIT_RELIGIOUS": -80, "PSEUDOYIELD_UNIT_TRADE": -60,
                 "PSEUDOYIELD_TOURISM": -100, "PSEUDOYIELD_SPACE_RACE": -80, "PSEUDOYIELD_HAPPINESS": -50},
         classes={"PROMOTION_CLASS_NAVAL_MELEE": 25, "PROMOTION_CLASS_NAVAL_RANGED": 25,
                  "PROMOTION_CLASS_NAVAL_RAIDER": 20, "PROMOTION_CLASS_NAVAL_CARRIER": 15},
         districts={"DISTRICT_HARBOR": 120}),
    dict(id=6, key="defense", group="posture",
         desc="walls and defending units at home; no attacks, fewer wonders",
         yields={"YIELD_PRODUCTION": 15, "YIELD_GOLD": 10},
         pseudo={"PSEUDOYIELD_CITY_DEFENSES": 100, "PSEUDOYIELD_CITY_DEFENDING_UNITS": 50,
                 "PSEUDOYIELD_UNIT_COMBAT": 30, "PSEUDOYIELD_CITY_BASE": -50,
                 "PSEUDOYIELD_WONDER": -30, "PSEUDOYIELD_UNIT_SETTLER": -30},
         classes={"PROMOTION_CLASS_RANGED": 15, "PROMOTION_CLASS_ANTI_CAVALRY": 15,
                  "PROMOTION_CLASS_SIEGE": -50},
         districts={"DISTRICT_ENCAMPMENT": 40}),
    dict(id=7, key="air_power", group="posture",
         desc="aircraft and aerodromes (needs Flight)",
         pseudo={"PSEUDOYIELD_UNIT_AIR_COMBAT": 100, "PSEUDOYIELD_STANDING_ARMY_VALUE": 15},
         classes={"PROMOTION_CLASS_AIR_FIGHTER": 20, "PROMOTION_CLASS_AIR_BOMBER": 20},
         districts={"DISTRICT_AERODROME": 80}),
    # ---- victory focus -----------------------------------------------------
    dict(id=8, key="science_victory", group="focus",
         desc="science, campuses, great scientists, space race",
         yields={"YIELD_SCIENCE": 40},
         pseudo={"PSEUDOYIELD_TECHNOLOGY": 25, "PSEUDOYIELD_GPP_SCIENTIST": 40, "PSEUDOYIELD_SPACE_RACE": 50},
         districts={"DISTRICT_CAMPUS": 60, "DISTRICT_SPACEPORT": 60}),
    dict(id=9, key="culture_victory", group="focus",
         desc="culture, tourism, theatres, great works, archaeologists, wonders",
         yields={"YIELD_CULTURE": 40},
         pseudo={"PSEUDOYIELD_CIVIC": 25, "PSEUDOYIELD_TOURISM": 60, "PSEUDOYIELD_GPP_ARTIST": 30,
                 "PSEUDOYIELD_GPP_MUSICIAN": 30, "PSEUDOYIELD_GPP_WRITER": 30,
                 "PSEUDOYIELD_GREATWORK_WRITING": 20, "PSEUDOYIELD_GREATWORK_PORTRAIT": 20,
                 "PSEUDOYIELD_GREATWORK_LANDSCAPE": 20, "PSEUDOYIELD_GREATWORK_SCULPTURE": 20,
                 "PSEUDOYIELD_GREATWORK_MUSIC": 20, "PSEUDOYIELD_GREATWORK_ARTIFACT": 20,
                 "PSEUDOYIELD_UNIT_ARCHAEOLOGIST": 40, "PSEUDOYIELD_WONDER": 25},
         classes={"PROMOTION_CLASS_ROCK_BAND": 20},
         districts={"DISTRICT_THEATER": 60}),
    dict(id=10, key="religious_victory", group="focus",
         desc="faith, holy sites, missionaries and apostles, spreading religion",
         yields={"YIELD_FAITH": 50},
         pseudo={"PSEUDOYIELD_UNIT_RELIGIOUS": 80, "PSEUDOYIELD_GPP_PROPHET": 60,
                 "PSEUDOYIELD_RELIGIOUS_CONVERT_EMPIRE": 50, "PSEUDOYIELD_GREATWORK_RELIC": 20,
                 "PSEUDOYIELD_GREATWORK_RELIGIOUS": 20},
         classes={"PROMOTION_CLASS_APOSTLE": 20},
         districts={"DISTRICT_HOLY_SITE": 60}),
    dict(id=11, key="diplomatic_victory", group="focus",
         desc="diplomatic favour and victory points, envoys and city-state influence",
         yields={"YIELD_GOLD": 15},
         pseudo={"PSEUDOYIELD_DIPLOMATIC_FAVOR": 50, "PSEUDOYIELD_DIPLOMATIC_VICTORY_POINT": 50,
                 "PSEUDOYIELD_INFLUENCE": 50, "PSEUDOYIELD_DIPLOMATIC_BONUS": 50,
                 "PSEUDOYIELD_DIPLOMATIC_GRIEVANCE": 30},
         districts={"DISTRICT_GOVERNMENT": 40, "DISTRICT_DIPLOMATIC_QUARTER": 60}),
    dict(id=12, key="domination_victory", group="focus",
         desc="take cities: stronger army, siege units, great generals",
         yields={"YIELD_PRODUCTION": 15},
         pseudo={"PSEUDOYIELD_CITY_BASE": 50, "PSEUDOYIELD_CITY_ORIGINAL_CAPITAL": 50,
                 "PSEUDOYIELD_UNIT_COMBAT": 60, "PSEUDOYIELD_STANDING_ARMY_VALUE": 30,
                 "PSEUDOYIELD_GPP_GENERAL": 40, "PSEUDOYIELD_TOURISM": -50},
         classes={"PROMOTION_CLASS_SIEGE": 20},
         districts={"DISTRICT_ENCAMPMENT": 60}),
    # ---- economy and empire ------------------------------------------------
    dict(id=13, key="fix_bankruptcy", group="focus",
         desc="gold first: trade routes and commercial hubs, stop building units and costly districts",
         yields={"YIELD_GOLD": 100},
         pseudo={"PSEUDOYIELD_STANDING_ARMY_NUMBER": -60, "PSEUDOYIELD_STANDING_ARMY_VALUE": -60,
                 "PSEUDOYIELD_UNIT_COMBAT": -60, "PSEUDOYIELD_UNIT_NAVAL_COMBAT": -60,
                 "PSEUDOYIELD_UNIT_AIR_COMBAT": -60, "PSEUDOYIELD_DISTRICT": -30,
                 "PSEUDOYIELD_WONDER": -30, "PSEUDOYIELD_UNIT_TRADE": 50, "PSEUDOYIELD_GPP_MERCHANT": 30},
         districts={"DISTRICT_COMMERCIAL_HUB": 80, "DISTRICT_HARBOR": 40}),
    dict(id=14, key="gold", group="focus",
         desc="more gold: commercial hubs, harbours, great merchants",
         yields={"YIELD_GOLD": 40},
         pseudo={"PSEUDOYIELD_GPP_MERCHANT": 30, "PSEUDOYIELD_UNIT_TRADE": 30},
         districts={"DISTRICT_COMMERCIAL_HUB": 60, "DISTRICT_HARBOR": 30}),
    dict(id=15, key="trade", group="focus",
         desc="traders and trade routes, commercial hubs and harbours",
         yields={"YIELD_GOLD": 15},
         pseudo={"PSEUDOYIELD_UNIT_TRADE": 100},
         districts={"DISTRICT_COMMERCIAL_HUB": 50, "DISTRICT_HARBOR": 40}),
    dict(id=16, key="amenities", group="focus",
         desc="happiness: entertainment districts, luxury resources",
         pseudo={"PSEUDOYIELD_HAPPINESS": 100, "PSEUDOYIELD_RESOURCE_LUXURY": 80},
         districts={"DISTRICT_ENTERTAINMENT_COMPLEX": 80, "DISTRICT_WATER_ENTERTAINMENT_COMPLEX": 60}),
    dict(id=17, key="growth", group="focus",
         desc="food, population and housing: aqueducts, neighbourhoods, farms",
         yields={"YIELD_FOOD": 50},
         pseudo={"PSEUDOYIELD_CITY_POPULATION": 50, "PSEUDOYIELD_IMPROVEMENT": 15},
         districts={"DISTRICT_AQUEDUCT": 60, "DISTRICT_NEIGHBORHOOD": 60}),
    dict(id=18, key="production", group="focus",
         desc="production: industrial zones, mines, great engineers",
         yields={"YIELD_PRODUCTION": 50},
         pseudo={"PSEUDOYIELD_GPP_ENGINEER": 30, "PSEUDOYIELD_IMPROVEMENT": 15},
         districts={"DISTRICT_INDUSTRIAL_ZONE": 70}),
    dict(id=19, key="expansion", group="focus",
         desc="settlers and new cities",
         pseudo={"PSEUDOYIELD_UNIT_SETTLER": 100, "PSEUDOYIELD_UNIT_EXPLORER": 20, "PSEUDOYIELD_WONDER": -20}),
    dict(id=20, key="improvements", group="focus",
         desc="builders and tile improvements",
         yields={"YIELD_FOOD": 10, "YIELD_PRODUCTION": 10},
         pseudo={"PSEUDOYIELD_IMPROVEMENT": 80}),
    dict(id=21, key="wonders", group="focus",
         desc="world wonders",
         yields={"YIELD_PRODUCTION": 15},
         pseudo={"PSEUDOYIELD_WONDER": 100, "PSEUDOYIELD_GPP_ENGINEER": 30}),
    dict(id=22, key="great_people", group="focus",
         desc="great people points of every kind",
         pseudo={"PSEUDOYIELD_GPP_ADMIRAL": 50, "PSEUDOYIELD_GPP_ARTIST": 50, "PSEUDOYIELD_GPP_ENGINEER": 50,
                 "PSEUDOYIELD_GPP_GENERAL": 50, "PSEUDOYIELD_GPP_MERCHANT": 50, "PSEUDOYIELD_GPP_MUSICIAN": 50,
                 "PSEUDOYIELD_GPP_PROPHET": 50, "PSEUDOYIELD_GPP_SCIENTIST": 50, "PSEUDOYIELD_GPP_WRITER": 50,
                 "PSEUDOYIELD_DISTRICT": 15}),
    dict(id=23, key="faith", group="focus",
         desc="faith for buying units and buildings: holy sites",
         yields={"YIELD_FAITH": 50},
         pseudo={"PSEUDOYIELD_GPP_PROPHET": 20},
         districts={"DISTRICT_HOLY_SITE": 50}),
    dict(id=24, key="exploration", group="focus",
         desc="scouts and exploring the map",
         pseudo={"PSEUDOYIELD_UNIT_EXPLORER": 100},
         classes={"PROMOTION_CLASS_RECON": 30}),
]

BY_ID = {c["id"]: c for c in CATEGORIES}
BY_KEY = {c["key"]: c for c in CATEGORIES}


def scaled(value: int, level: int) -> int:
    v = value * LEVEL_MULT[level]
    return max(v, -100)


def strategy_type(cat: dict, level: int) -> str:
    return f"CIV6AI_PRIO_{cat['key'].upper()}_{LEVELS[level].upper()}"


def lua_fn(cat: dict, level: int) -> str:
    return f"Civ6AiPrio_{cat['id']}_{level}"


# ---------------------------------------------------------------------------
# Model integration: legal commands, prompt block, reply parsing.
# ---------------------------------------------------------------------------
COMMAND_KIND = "set_build_priority"
REPLY_KEY = "priorities"


def command_id(cat_id: int, level: int) -> str:
    return f"CMD_PRIO_{cat_id}_{level}"


def current_levels(snapshot: dict) -> dict[int, int]:
    """Active priorities of the seat, from civ6.priorities (written by the mod)."""
    out: dict[int, int] = {}
    block = snapshot.get("civ6") if isinstance(snapshot, dict) else None
    items = block.get("priorities") if isinstance(block, dict) else None
    for item in items or []:
        if not isinstance(item, dict):
            continue
        try:
            cid, lvl = int(item.get("id")), int(item.get("level"))
        except (TypeError, ValueError):
            continue
        if cid in BY_ID and 1 <= lvl <= 3:
            out[cid] = lvl
    return out


def priorities_supported(snapshot: dict) -> bool:
    """Only seats whose mod build reports civ6.priorities get the command."""
    block = snapshot.get("civ6") if isinstance(snapshot, dict) else None
    return isinstance(block, dict) and isinstance(block.get("priorities"), list)


def inject_legal_commands(snapshot: dict) -> int:
    """Add one legal command per category and level (0 switches it off)."""
    if not priorities_supported(snapshot):
        return 0
    from sidecar.civ6_adapter import _enrich_runtime_legal_command

    legal = snapshot.setdefault("legal_commands", [])
    have = {c.get("command_id") for c in legal if isinstance(c, dict)}
    added = 0
    for cat in CATEGORIES:
        for level in (0, 1, 2, 3):
            cid = command_id(cat["id"], level)
            if cid in have:
                continue
            legal.append(_enrich_runtime_legal_command({
                "command_id": cid,
                "kind": COMMAND_KIND,
                "description": f"build priority {cat['key']}:{level}",
                "fixed_arguments": {"priority_id": cat["id"], "priority_level": level},
            }))
            added += 1
    return added


def _fmt(levels: dict[int, int]) -> str:
    if not levels:
        return "none"
    return ", ".join(f"{BY_ID[c]['key']}:{lvl}" for c, lvl in sorted(levels.items()))


def prompt_lines(snapshot: dict) -> list[str]:
    """=== BUILD PRIORITIES === block for the prompt (empty when unsupported)."""
    if not priorities_supported(snapshot):
        return []
    posture = " | ".join(f"{c['key']} ({c['desc']})" for c in CATEGORIES if c["group"] == "posture")
    focus = " | ".join(f"{c['key']} ({c['desc']})" for c in CATEGORIES if c["group"] == "focus")
    return [
        "=== BUILD PRIORITIES ===",
        "Your cities' production is chosen by the game's own AI. Build priorities steer what it builds across "
        "your whole empire (which units, buildings, districts and wonders it favours). They stay on every turn "
        "until you change them.",
        f"Current: {_fmt(current_levels(snapshot))}",
        "Levels: 1 = light, 2 = strong, 3 = all-in (almost nothing else gets built).",
        f"Pick at most ONE posture: {posture}",
        f"Pick at most {MAX_FOCUS} focuses: {focus}",
        f'To change them, add the optional key "{REPLY_KEY}" with your COMPLETE new set, e.g. '
        f'"{REPLY_KEY}": "war:2, production:1, expansion:1". Anything you leave out is switched off. '
        f'"{REPLY_KEY}": "none" switches all off. Omit the key to keep the current set.',
        "Change them when your situation changes (war starts or ends, bankruptcy, a victory plan), not every turn.",
    ]


def parse_reply(value) -> tuple[dict[int, int] | None, list[str]]:
    """Desired complete set from the model's value, plus problems. None = no change."""
    problems: list[str] = []
    if value is None:
        return None, problems
    if isinstance(value, dict):
        items = [f"{k}:{v}" for k, v in value.items()]
    elif isinstance(value, list):
        items = [str(v) for v in value]
    else:
        text = str(value).strip()
        if not text or text.lower() in ("keep", "same", "unchanged", "no change"):
            return None, problems
        if text.lower() in ("none", "clear", "off", "0"):
            return {}, problems
        items = [p for p in text.replace(";", ",").replace("+", ",").split(",")]
    wanted: dict[int, int] = {}
    for raw in items:
        part = raw.strip().strip('"').strip()
        if not part:
            continue
        key, _, lvl_text = part.partition(":")
        key = key.strip().lower().replace(" ", "_").replace("-", "_")
        lvl_text = lvl_text.strip().lower()
        if lvl_text in LEVEL_BY_NAME:
            level = LEVEL_BY_NAME[lvl_text]
        elif lvl_text in ("all-in", "allin"):
            level = 3
        elif lvl_text == "":
            level = 1
        else:
            try:
                level = int(lvl_text)
            except ValueError:
                problems.append(f"bad_level:{part}")
                continue
        cat = BY_KEY.get(key)
        if cat is None:
            problems.append(f"unknown_priority:{key}")
            continue
        if not 0 <= level <= 3:
            problems.append(f"bad_level:{part}")
            continue
        if level > 0:
            wanted[cat["id"]] = level
    postures = [c for c in wanted if BY_ID[c]["group"] == "posture"]
    if len(postures) > 1:
        # Keep the first posture listed (dict keeps insertion order).
        for c in postures[1:]:
            del wanted[c]
        problems.append("too_many_postures")
    focuses = [c for c in wanted if BY_ID[c]["group"] == "focus"]
    if len(focuses) > MAX_FOCUS:
        for c in focuses[MAX_FOCUS:]:
            del wanted[c]
        problems.append("too_many_focus")
    return wanted, problems


def plan_commands(current: dict[int, int], wanted: dict[int, int]) -> list[str]:
    """Legal command ids, switches-off first so a swap never hits the focus cap."""
    offs = [command_id(c, 0) for c in sorted(current) if c not in wanted]
    postures = [command_id(c, l) for c, l in wanted.items() if BY_ID[c]["group"] == "posture" and current.get(c) != l]
    focuses = [command_id(c, l) for c, l in wanted.items() if BY_ID[c]["group"] == "focus" and current.get(c) != l]
    return offs + postures + focuses
