"""Generate mod/Civ6Ai/Data/Civ6Ai_Priorities.sql from sidecar/civ6_priorities.py.

Run from the repo root:  python scripts/gen_priorities.py
Every item row is written as INSERT ... SELECT from the table that defines it,
so an item missing from the loaded rulesets (an expansion or DLC that is off)
is skipped instead of failing the whole file. Districts also favour each
civilization's unique replacement (DistrictReplaces).
"""
from __future__ import annotations

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from sidecar import civ6_priorities as P  # noqa: E402

OUT = os.path.join(ROOT, "mod", "Civ6Ai", "Data", "Civ6Ai_Priorities.sql")
ORDERS_LUA = os.path.join(ROOT, "mod", "Civ6Ai", "Gameplay", "Civ6Ai_Orders.lua")
LUA_BEGIN = "-- BEGIN GENERATED PRIORITY_IDS (scripts/gen_priorities.py)"
LUA_END = "-- END GENERATED PRIORITY_IDS"

SYSTEMS = [
    # spec field, list suffix, AiLists system, defining table, key column
    ("yields", "Yields", "Yields", "Yields", "YieldType"),
    ("pseudo", "PseudoYields", "PseudoYields", "PseudoYields", "PseudoYieldType"),
    ("classes", "UnitBuilds", "UnitPromotionClasses", "UnitPromotionClasses", "PromotionClassType"),
    ("districts", "Districts", "Districts", "Districts", "DistrictType"),
]


def q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def build() -> str:
    out = [
        "-- GENERATED by scripts/gen_priorities.py from sidecar/civ6_priorities.py. Do not edit by hand.",
        "-- Civ6Ai build priorities: one engine AI strategy per category and level. Each is",
        "-- active when gameplay Lua (GameEvents.Civ6AiPrio_<id>_<level>) answers true, which it",
        "-- does from the synced game property CIV6AI_PRIO_<player>_<id>.",
        "",
    ]
    for cat in P.CATEGORIES:
        for level in P.LEVELS:
            st = P.strategy_type(cat, level)
            out.append(f"-- {cat['key']} ({P.LEVELS[level]}): {cat['desc']}")
            out.append(f"INSERT INTO Types (Type, Kind) VALUES ({q(st)}, 'KIND_VICTORY_STRATEGY');")
            out.append(f"INSERT INTO Strategies (StrategyType, VictoryType, NumConditionsNeeded) VALUES ({q(st)}, NULL, 1);")
            out.append("INSERT INTO StrategyConditions (StrategyType, ConditionFunction, Disqualifier) "
                       f"VALUES ({q(st)}, 'Is Not Major', 1);")
            out.append("INSERT INTO StrategyConditions (StrategyType, ConditionFunction, StringValue, ThresholdValue) "
                       f"VALUES ({q(st)}, 'Call Lua Function', {q(P.lua_fn(cat, level))}, 0);")
            for field, suffix, system, table, col in SYSTEMS:
                items = cat.get(field) or {}
                if not items:
                    continue
                lt = f"{st}_{suffix}"
                out.append(f"INSERT INTO AiListTypes (ListType) VALUES ({q(lt)});")
                out.append(f"INSERT INTO AiLists (ListType, System) VALUES ({q(lt)}, {q(system)});")
                out.append(f"INSERT INTO Strategy_Priorities (StrategyType, ListType) VALUES ({q(st)}, {q(lt)});")
                for item, value in items.items():
                    v = P.scaled(value, level)
                    out.append("INSERT INTO AiFavoredItems (ListType, Item, Favored, Value) "
                               f"SELECT {q(lt)}, {col}, 1, {v} FROM {table} WHERE {col} = {q(item)};")
                    if field == "districts":
                        out.append("INSERT INTO AiFavoredItems (ListType, Item, Favored, Value) "
                                   f"SELECT {q(lt)}, CivUniqueDistrictType, 1, {v} FROM DistrictReplaces "
                                   f"WHERE ReplacesDistrictType = {q(item)};")
            out.append("")
    return "\n".join(out)


def lua_block() -> str:
    lines = [LUA_BEGIN, "Civ6Ai_Orders.PRIORITY_IDS = {"]
    for cat in P.CATEGORIES:
        lines.append(f'  {{ id = {cat["id"]}, key = "{cat["key"]}", group = "{cat["group"]}" }},')
    lines.append("}")
    lines.append(f"Civ6Ai_Orders.PRIORITY_MAX_FOCUS = {P.MAX_FOCUS}")
    lines.append(f"Civ6Ai_Orders.PRIORITY_MAX_LEVEL = {max(P.LEVELS)}")
    lines.append(LUA_END)
    return "\n".join(lines)


def update_lua(path: str = ORDERS_LUA) -> bool:
    """Rewrite the PRIORITY_IDS block in Civ6Ai_Orders.lua. Returns True if it changed."""
    with open(path, encoding="utf-8") as f:
        text = f.read()
    a = text.index(LUA_BEGIN)
    b = text.index(LUA_END, a) + len(LUA_END)
    new = text[:a] + lua_block() + text[b:]
    if new != text:
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(new)
    return new != text


def main() -> int:
    update_lua()
    text = build()
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUT} ({len(P.CATEGORIES)} categories, {text.count('INSERT INTO Strategies ')} strategies)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
