#!/usr/bin/env python3
"""Copy mod/Civ6Ai into both possible Civ6 Mods folders, with timestamped backups.

By default the installed copy also gets a generated live configuration so the
single-player live test works without the old testbed ModSync script:

- Mods/Civ6Ai/InGame/Civ6Ai_Paths.lua, the one host config file the game reads
  (repo path, python, civ6ai root, sidecar_live=1, managed seats, session id,
  sidecar timeout)
- <My Games>/civ6ai/runtime.json for the host bridge (scripts/live_lua_bridge.py);
  an existing runtime.json is backed up first.

The repo copy of Civ6Ai_Paths.lua stays a neutral stub (what a friend's PC runs
with). Use --stub-only to install the plain stub (no live config).

Usage:
  python scripts/install_mod.py
  python scripts/install_mod.py --managed-seats 1 --sidecar-timeout 600
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "mod" / "Civ6Ai"
MEIER = "Sid Meier's Civilization VI"
DEFAULT_MANAGED_SEATS = ""  # empty = every AI major (and the local human when autotest is on)


def mods_targets() -> list[Path]:
    home = Path.home()
    return [
        home / "OneDrive" / "Documents" / "My Games" / MEIER / "Mods" / "Civ6Ai",
        home / "Documents" / "My Games" / MEIER / "Mods" / "Civ6Ai",
    ]


def copy_tree(src: Path, dst: Path) -> int:
    n = 0
    dst.mkdir(parents=True, exist_ok=True)
    for f in src.rglob("*"):
        if not f.is_file():
            continue
        if "__pycache__" in f.parts or f.suffix == ".pyc":
            continue
        out = dst / f.relative_to(src)
        out.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(f, out)
        n += 1
    return n


BACKUP_DIRNAME = "Civ6Ai_mod_backups"


def backup_root(dst: Path) -> Path:
    """Backups live next to Mods (not inside it) so Civ6 never loads a stale duplicate .modinfo."""
    return dst.parent.parent / BACKUP_DIRNAME


def backup_existing(dst: Path) -> Path | None:
    if not dst.exists():
        return None
    stamp = time.strftime("%Y%m%d-%H%M%S")
    root = backup_root(dst)
    root.mkdir(parents=True, exist_ok=True)
    backup = root / f"{dst.name}.bak-{stamp}"
    if backup.exists():
        shutil.rmtree(backup)
    shutil.move(str(dst), str(backup))
    return backup


def relocate_legacy_backups(dst: Path) -> list[Path]:
    """Move old Mods/Civ6Ai.bak-* folders (duplicate mod ids) out of the Mods folder."""
    mods_dir = dst.parent
    moved: list[Path] = []
    if not mods_dir.is_dir():
        return moved
    for legacy in sorted(mods_dir.glob(f"{dst.name}.bak-*")):
        if not legacy.is_dir():
            continue
        root = backup_root(dst)
        root.mkdir(parents=True, exist_ok=True)
        target = root / legacy.name
        if target.exists():
            target = root / (legacy.name + "-" + time.strftime("%H%M%S"))
        shutil.move(str(legacy), str(target))
        moved.append(target)
    return moved


def _lua_str(value: object) -> str:
    """Lua double-quoted string literal (forward slashes, escaped quotes)."""
    text = str(value).replace("\\", "/")
    return '"' + text.replace('"', '\\"') + '"'


def _fwd(path: Path | str) -> str:
    return str(path).replace("\\", "/")


def normalize_seats(value: str) -> str:
    """Comma list of seats, or empty for 'every AI major' (plus local human in autotest)."""
    seats = []
    for token in str(value or "").split(","):
        token = token.strip()
        if token:
            int(token)  # raises ValueError on junk
            if token not in seats:
                seats.append(token)
    return ",".join(seats)


def live_settings(
    *,
    civ6ai_root: Path,
    log_dir: Path | None,
    managed_seats: str,
    session_id: str,
    sidecar_timeout: int,
    autotest: bool = True,
    stop_turn: int = 0,
    mp_test: bool = False,
    python: str | None = None,
    repo: Path | None = None,
) -> dict:
    return {
        "python": _fwd(python or Path(sys.executable).resolve()),
        "repo": _fwd(repo or ROOT),
        "root": _fwd(civ6ai_root),
        "log_dir": _fwd(log_dir) if log_dir else "",
        "managed_seats": normalize_seats(managed_seats),
        "session_id": session_id,
        "sidecar_timeout_seconds": max(30, int(sidecar_timeout)),
        "sidecar_live": 1,
        "autotest": 1 if autotest else 0,
        "autotest_stop_turn": max(1, int(stop_turn)) if stop_turn else 0,
        "fast_end_turn": 0,
        "mp_test": 1 if mp_test else 0,
    }


def render_paths_lua(s: dict) -> str:
    return (
        "-- Generated by scripts/install_mod.py (live config). Re-run install_mod.py to change.\n"
        "Civ6Ai_Paths = {\n"
        f"  Python = {_lua_str(s['python'])},\n"
        f"  Repo = {_lua_str(s['repo'])},\n"
        f"  Civ6AiRoot = {_lua_str(s['root'])},\n"
        f"  LogDir = {_lua_str(s['log_dir'])},\n"
        f"  SidecarTimeoutSeconds = {int(s['sidecar_timeout_seconds'])},\n"
        '  SidecarScript = "sidecar/run_civ6.py",\n'
        "  SeatExperiment = 0,\n"
        f"  Autotest = {int(s['autotest'])},\n"
        + (f"  AutotestStopTurn = {int(s['autotest_stop_turn'])},\n" if s.get('autotest_stop_turn') else "")
        + f"  SidecarLive = {int(s['sidecar_live'])},\n"
        f"  FastEndTurn = {int(s['fast_end_turn'])},\n"
        f"  ManagedSeats = {_lua_str(s['managed_seats'])},\n"
        f"  SessionId = {_lua_str(s['session_id'])},\n"
        "  EnableSinglePlayerChat = 1,\n"
        "  -- 1 = host runs the scripted two-PC multiplayer test (docs/MP_TEST_MODE.md).\n"
        f"  MpTest = {int(s.get('mp_test', 0))},\n"
        "}\n"
    )


def write_mod_live_config(mod_dir: Path, settings: dict) -> None:
    (mod_dir / "InGame" / "Civ6Ai_Paths.lua").write_text(render_paths_lua(settings), encoding="utf-8")


def write_runtime_json(civ6ai_root: Path, settings: dict, extra_session_roots: list[Path] | None = None) -> Path | None:
    """Write <civ6ai_root>/runtime.json for the host bridge. Returns the backup path, if any."""
    civ6ai_root.mkdir(parents=True, exist_ok=True)
    path = civ6ai_root / "runtime.json"
    backup = None
    if path.is_file():
        backup = path.with_name("runtime.json.bak-" + time.strftime("%Y%m%d-%H%M%S"))
        shutil.copy2(path, backup)
    payload = {
        "python": settings["python"],
        "root": settings["root"],
        "repo": settings["repo"],
        "session_id": settings["session_id"],
        "sidecar_live": settings["sidecar_live"],
        "managed_seats": settings["managed_seats"],
        "sidecar_timeout_seconds": settings["sidecar_timeout_seconds"],
        "autotest": settings["autotest"],
        "fast_end_turn": settings["fast_end_turn"],
        "mp_test": settings.get("mp_test", 0),
    }
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    for root in [civ6ai_root] + list(extra_session_roots or []):
        session = root / "sessions" / settings["session_id"]
        session.mkdir(parents=True, exist_ok=True)
        for seat in str(settings["managed_seats"] or "").split(","):
            seat = seat.strip()
            if seat:
                (session / f"PLAYER_{seat}").mkdir(parents=True, exist_ok=True)
    return backup


# Per-player files that belong to one game. A new session archives them so a
# prior game's answers can never be picked up and republished.
TRANSIENT_PATTERNS = (
    "decision*.json",
    "apply_commands*.json",
    "snapshot*.json",
    "apply_turn_*.done",
    "apply_chat_*.done",
    "inbox_inject_turn_*.done",
    "sidecar_job.json",
    "inbox*.json",
    "inbox*.txt",
)

_SESSION_LINE = re.compile(r'(^\s*SessionId\s*=\s*)"[^"\r\n]*"', re.MULTILINE)


def new_session_id(prefix: str = "live", taken: str | None = None) -> str:
    sid = f"{prefix}-{time.strftime('%Y%m%d-%H%M%S')}"
    if taken and sid == taken:
        sid += "b"
    return sid


def set_session_in_lua(text: str, session_id: str) -> tuple[str, int]:
    """Replace the SessionId string in a generated Civ6Ai_Paths module."""
    return _SESSION_LINE.subn(lambda m: m.group(1) + _lua_str(session_id), text)


def archive_session_transients(session_dir: Path, stamp: str | None = None) -> int:
    """Move per-player transient files of session_dir into session_dir/_archive_<stamp>/."""
    if not session_dir.is_dir():
        return 0
    stamp = stamp or time.strftime("%Y%m%d_%H%M%S")
    moved = 0
    for player_dir in sorted(session_dir.glob("PLAYER_*")):
        if not player_dir.is_dir():
            continue
        for pattern in TRANSIENT_PATTERNS:
            for path in sorted(player_dir.glob(pattern)):
                if not path.is_file():
                    continue
                dest = session_dir / f"_archive_{stamp}" / player_dir.name / path.name
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(path), str(dest))
                moved += 1
    return moved


def rotate_session(
    session_id: str | None = None,
    *,
    civ6ai_root: Path | None = None,
    mod_dirs: list[Path] | None = None,
    log_dir: Path | None = None,
) -> dict:
    """Start a new live session for the next game without reinstalling the mod.

    Rewrites SessionId in the installed Civ6Ai_Paths.lua (read by Civ6 when a
    game loads, so it must run before the game starts) and in
    runtime.json (read by the host bridge), creates the PLAYER_* dirs, and archives
    per-player transient files of the previous and the new session.
    """
    root = civ6ai_root or default_civ6ai_root()
    runtime_path = root / "runtime.json"
    runtime: dict = {}
    if runtime_path.is_file():
        try:
            runtime = json.loads(runtime_path.read_text(encoding="utf-8-sig"))
        except (OSError, ValueError):
            runtime = {}
    old = str(runtime.get("session_id") or "")
    new = session_id or new_session_id(taken=old)
    updated: list[str] = []
    for mod_dir in mod_dirs if mod_dirs is not None else mods_targets():
        path = mod_dir / "InGame" / "Civ6Ai_Paths.lua"
        if not path.is_file():
            continue
        raw = path.read_bytes().decode("utf-8")
        text, count = set_session_in_lua(raw, new)
        if count:
            path.write_bytes(text.encode("utf-8"))
            updated.append(str(path))
    runtime["session_id"] = new
    root.mkdir(parents=True, exist_ok=True)
    runtime_path.write_text(json.dumps(runtime, indent=2) + "\n", encoding="utf-8")
    roots = [root]
    if log_dir is None:
        log_dir = default_log_dir()
    if log_dir is not None:
        roots.append(Path(log_dir) / "civ6ai")
    stamp = time.strftime("%Y%m%d_%H%M%S")
    archived = 0
    seats = [s for s in str(runtime.get("managed_seats") or "").split(",") if s.strip()]
    for base in roots:
        for sid in {old, new} - {""}:
            archived += archive_session_transients(base / "sessions" / sid, stamp)
        for seat in seats:
            (base / "sessions" / new / f"PLAYER_{seat.strip()}").mkdir(parents=True, exist_ok=True)
    return {"old": old, "new": new, "updated": updated, "archived": archived}


def default_civ6ai_root() -> Path:
    """Same root scripts/live_lua_bridge.py uses: first My Games root + /civ6ai."""
    sys.path.insert(0, str(ROOT / "scripts"))
    from civ6_paths import my_games_roots

    return my_games_roots()[0] / "civ6ai"


def default_log_dir() -> Path | None:
    sys.path.insert(0, str(ROOT / "scripts"))
    from civ6_paths import lua_log_candidates

    candidates = lua_log_candidates()
    for candidate in candidates:
        if candidate.is_file():
            return candidate.parent
    return candidates[0].parent if candidates else None


def _config_timeout() -> int:
    try:
        if str(ROOT) not in sys.path:
            sys.path.insert(0, str(ROOT))
        from sidecar.civ6_config import load_local_config

        return int(load_local_config().timeout_seconds)
    except Exception:
        return 600


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    timeout_default = _config_timeout()
    parser = argparse.ArgumentParser(description="Install Civ6Ai mod (+ live config) into Civ6 Mods folders")
    parser.add_argument("--managed-seats", default=DEFAULT_MANAGED_SEATS,
                        help="LLM seats, comma separated. Empty (default) = every AI major "
                             "(and the local human while autotest is on)")
    parser.add_argument("--sidecar-timeout", type=int, default=timeout_default,
                        help="Seconds the game/bridge wait for one LLM decision (default: config timeout_seconds)")
    parser.add_argument("--session-id", default="", help="Session id (default: live-<timestamp>)")
    parser.set_defaults(autotest=True)
    parser.add_argument("--autotest", action="store_true",
                        help="Unattended: LLM plays the local human seat and ends its turns (default on)")
    parser.add_argument("--no-autotest", dest="autotest", action="store_false",
                        help="You play the local human seat; only AI majors are model-driven")
    parser.add_argument("--stop-turn", type=int, default=0,
                        help="With --autotest: stop auto-ending turns after this game turn (default: mod default 20)")
    parser.add_argument("--mp-test", action="store_true",
                        help="Host PC only: run the scripted two-PC multiplayer test in the next network game")
    parser.add_argument("--stub-only", action="store_true", help="Install plain stubs; no live config / runtime.json")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if not SRC.is_dir():
        print(f"ERROR: missing {SRC}", file=sys.stderr)
        return 1
    settings = None
    if not args.stub_only:
        try:
            settings = live_settings(
                civ6ai_root=default_civ6ai_root(),
                log_dir=default_log_dir(),
                managed_seats=args.managed_seats,
                session_id=args.session_id or ("live-" + time.strftime("%Y%m%d-%H%M%S")),
                sidecar_timeout=args.sidecar_timeout,
                autotest=args.autotest,
                stop_turn=args.stop_turn,
                mp_test=args.mp_test,
            )
        except ValueError as error:
            print(f"ERROR: --managed-seats: {error}", file=sys.stderr)
            return 2
    installed = 0
    for t in mods_targets():
        parent = t.parent
        # Only install into trees that already exist OR create Mods under My Games if Documents exists.
        my_games = parent.parent  # .../My Games/Civ6
        docs_root = my_games.parent  # .../My Games
        if not docs_root.exists() and not my_games.exists():
            print(f"Skip (My Games path missing): {t}")
            continue
        parent.mkdir(parents=True, exist_ok=True)
        for moved in relocate_legacy_backups(t):
            print(f"Moved old backup out of Mods -> {moved}")
        backup = backup_existing(t)
        if backup is not None:
            print(f"Backup -> {backup}")
        n = copy_tree(SRC, t)
        if settings is not None:
            write_mod_live_config(t, settings)
        installed += 1
        print(f"Installed {n} files -> {t}")
    if installed == 0:
        print(
            "WARNING: no Mods targets were writable. Create "
            f"Documents/My Games/{MEIER}/Mods manually, then re-run.",
            file=sys.stderr,
        )
        return 1
    if settings is not None:
        mirror = [Path(settings["log_dir"]) / "civ6ai"] if settings["log_dir"] else []
        previous_session = ""
        try:
            previous_session = str(
                json.loads((Path(settings["root"]) / "runtime.json").read_text(encoding="utf-8-sig")).get("session_id") or ""
            )
        except (OSError, ValueError, AttributeError):
            pass
        backup = write_runtime_json(Path(settings["root"]), settings, mirror)
        if previous_session and previous_session != settings["session_id"]:
            archived = sum(
                archive_session_transients(base / "sessions" / previous_session)
                for base in [Path(settings["root"])] + mirror
            )
            if archived:
                print(f"Archived {archived} transient file(s) of previous session {previous_session}")
        if backup is not None:
            print(f"runtime.json backup -> {backup}")
        print(
            "Live config: autotest={autotest} managed_seats={seats} session={session_id} "
            "sidecar_timeout={sidecar_timeout_seconds}s repo={repo}".format(
                seats=settings["managed_seats"] or "all",
                **settings,
            )
        )
        print(f"runtime.json -> {Path(settings['root']) / 'runtime.json'}")
    else:
        print("Stub-only install (no live config).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
