"""Inject Civ5Ai apply payloads into the hidden InGame inbox."""
from __future__ import annotations

import base64
import ctypes
import logging
import sys
import time
from pathlib import Path

log = logging.getLogger(__name__)

INBOX_CLIENT_X = 640
INBOX_CLIENT_Y = 12
VK_RETURN = 0x0D
SW_RESTORE = 9
ASFW_ANY = 0xFFFFFFFF
CF_UNICODETEXT = 13
GMEM_MOVEABLE = 0x0002
VK_CONTROL = 0x11
VK_V = 0x56
KEYEVENTF_KEYUP = 0x0002
MOUSEEVENTF_LEFTDOWN = 0x0002
MOUSEEVENTF_LEFTUP = 0x0004

# Win32 inject is Windows-only; pending-apply Lua writes still work elsewhere.
_IS_WINDOWS = sys.platform.startswith("win")
_user32 = None
_kernel32 = None
_WNDENUMPROC = None
wintypes = None

if _IS_WINDOWS:
    from ctypes import wintypes as _wintypes

    wintypes = _wintypes
    _user32 = ctypes.windll.user32
    _kernel32 = ctypes.windll.kernel32
    _WNDENUMPROC = ctypes.WINFUNCTYPE(ctypes.c_bool, ctypes.c_void_p, ctypes.c_void_p)
    _kernel32.GlobalAlloc.restype = ctypes.c_void_p
    _kernel32.GlobalAlloc.argtypes = [ctypes.c_uint, ctypes.c_size_t]
    _kernel32.GlobalLock.restype = ctypes.c_void_p
    _kernel32.GlobalLock.argtypes = [ctypes.c_void_p]
    _kernel32.GlobalUnlock.argtypes = [ctypes.c_void_p]
    _user32.SetClipboardData.restype = ctypes.c_void_p
    _user32.SetClipboardData.argtypes = [ctypes.c_uint, ctypes.c_void_p]
    _user32.GetForegroundWindow.restype = ctypes.c_void_p
    _user32.SetForegroundWindow.argtypes = [ctypes.c_void_p]
    _user32.ClientToScreen.argtypes = [ctypes.c_void_p, ctypes.c_void_p]


APPLY_PENDING_LUA = "apply_pending.lua"


def _is_onedrive_path(path: Path) -> bool:
    return "onedrive" in str(path).replace("\\", "/").lower()


def civ5_my_games_roots() -> list[Path]:
    home = Path.home()
    candidates = [
        home / "Documents/My Games/Sid Meier's Civilization 5",
        home / "OneDrive/Documents/My Games/Sid Meier's Civilization 5",
    ]
    existing = [path for path in candidates if path.exists()]

    def _looks_like_civ5(path: Path) -> bool:
        return (
            (path / "config.ini").is_file()
            or (path / "Logs" / "Lua.log").is_file()
        )

    with_game = [path for path in existing if _looks_like_civ5(path)]
    pool = with_game or existing or [candidates[0]]
    local = [path for path in pool if not _is_onedrive_path(path)]
    chosen = local or pool
    unique: list[Path] = []
    seen: set[str] = set()
    for path in chosen:
        key = str(path.resolve()) if path.exists() else str(path)
        if key in seen:
            continue
        seen.add(key)
        unique.append(path)
    return unique


def civ5_apply_pending_dirs() -> list[Path]:
    """Mod runtime folder only. Lua/ is VFS-indexed; runtime/ is not in the modinfo."""
    return [root / "MODS" / "Civ5Ai" / "runtime" for root in civ5_my_games_roots()]


def write_pending_apply_lua(payload: str, session_id: str, player: int, turn: int) -> None:
    if not payload:
        return
    encoded = base64.b64encode(payload.encode("utf-8")).decode("ascii")
    content = (
        "-- autogenerated by civ5ai host\n"
        f'Civ5Ai_ApplyPendingMeta = {{ session_id = "{session_id}", player = {player}, turn = {turn} }}\n'
        f'Civ5Ai_ApplyPendingB64 = "{encoded}"\n'
    )
    for directory in civ5_apply_pending_dirs():
        path = directory / APPLY_PENDING_LUA
        try:
            directory.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            log.info(
                "Wrote pending apply lua %s session=%s player=%s turn=%s len=%d",
                path,
                session_id,
                player,
                turn,
                len(payload),
            )
        except OSError as error:
            log.warning("pending apply write failed %s: %s", path, error)


def clear_pending_apply_lua() -> None:
    for directory in civ5_apply_pending_dirs():
        path = directory / APPLY_PENDING_LUA
        try:
            if path.is_file():
                path.unlink()
                log.info("Cleared pending apply lua %s", path)
        except OSError as error:
            log.warning("pending apply delete failed %s: %s", path, error)


def build_apply_full_line(payload: str, session_id: str, player: int, turn: int) -> str:
    encoded = base64.b64encode(payload.encode("utf-8")).decode("ascii")
    return f"CIV5AI|apply|full|{player}|{turn}|{session_id}|{encoded}"


def build_apply_lines(
    payload: str,
    session_id: str,
    player: int,
    turn: int,
) -> list[str]:
    return [build_apply_full_line(payload, session_id, player, turn)]


def _civ5_hwnd() -> int:
    found: list[int] = []

    def _cb(hwnd: int, _lparam: int) -> bool:
        if not _user32.IsWindowVisible(hwnd):
            return True
        length = _user32.GetWindowTextLengthW(hwnd)
        buf = ctypes.create_unicode_buffer(length + 1)
        _user32.GetWindowTextW(hwnd, buf, length + 1)
        title = buf.value or ""
        if "Civilization V" in title or title.startswith("CivilizationV"):
            found.append(int(hwnd))
        return True

    _user32.EnumWindows(_WNDENUMPROC(_cb), 0)
    return found[0] if found else 0


def _focus_civ5(hwnd: int) -> None:
    _user32.ShowWindow(hwnd, SW_RESTORE)
    try:
        _user32.AllowSetForegroundWindow(ASFW_ANY)
    except Exception:
        pass
    foreground = _user32.GetForegroundWindow()
    fg_tid = _user32.GetWindowThreadProcessId(foreground, None)
    target_tid = _user32.GetWindowThreadProcessId(hwnd, None)
    cur_tid = _kernel32.GetCurrentThreadId()
    if fg_tid and fg_tid != cur_tid:
        _user32.AttachThreadInput(cur_tid, fg_tid, True)
    if target_tid and target_tid != cur_tid and target_tid != fg_tid:
        _user32.AttachThreadInput(cur_tid, target_tid, True)
    _user32.SetForegroundWindow(hwnd)
    _user32.BringWindowToTop(hwnd)
    if fg_tid and fg_tid != cur_tid:
        _user32.AttachThreadInput(cur_tid, fg_tid, False)
    if target_tid and target_tid != cur_tid and target_tid != fg_tid:
        _user32.AttachThreadInput(cur_tid, target_tid, False)


def _set_clipboard(text: str) -> None:
    payload = text.encode("utf-16-le") + b"\x00\x00"
    if not _user32.OpenClipboard(None):
        raise OSError("OpenClipboard failed")
    try:
        _user32.EmptyClipboard()
        handle = _kernel32.GlobalAlloc(GMEM_MOVEABLE, len(payload))
        if not handle:
            raise OSError("GlobalAlloc failed")
        locked = _kernel32.GlobalLock(handle)
        if not locked:
            raise OSError("GlobalLock failed")
        ctypes.memmove(locked, payload, len(payload))
        _kernel32.GlobalUnlock(handle)
        if not _user32.SetClipboardData(CF_UNICODETEXT, handle):
            raise OSError("SetClipboardData failed")
    finally:
        _user32.CloseClipboard()


def _key(vk: int, up: bool = False) -> None:
    _user32.keybd_event(vk, 0, KEYEVENTF_KEYUP if up else 0, 0)


def _enable_dpi_aware() -> None:
    try:
        ctypes.windll.shcore.SetProcessDpiAwareness(2)
    except Exception:
        try:
            _user32.SetProcessDPIAware()
        except Exception:
            pass


_enable_dpi_aware()


def _click_client(hwnd: int, client_x: int, client_y: int) -> None:
    point = wintypes.POINT(client_x, client_y)
    _user32.ClientToScreen(hwnd, ctypes.byref(point))
    _user32.SetCursorPos(point.x, point.y)
    _user32.mouse_event(MOUSEEVENTF_LEFTDOWN, 0, 0, 0, 0)
    _user32.mouse_event(MOUSEEVENTF_LEFTUP, 0, 0, 0, 0)


def _client_size(hwnd: int) -> tuple[int, int]:
    rect = wintypes.RECT()
    _user32.GetClientRect(hwnd, ctypes.byref(rect))
    return int(rect.right), int(rect.bottom)


def release_ui_focus() -> bool:
    """Click the map so HostInbox/chat EditBoxes lose keyboard focus.

    Game.DoControl(CONTROL_ENDTURN) no-ops while UI.isFocused() is true.
    """
    hwnd = _civ5_hwnd()
    if not hwnd:
        return False
    width, height = _client_size(hwnd)
    x = max(80, width // 3)
    y = max(80, height // 2)
    _focus_civ5(hwnd)
    time.sleep(0.08)
    _click_client(hwnd, x, y)
    return True


def press_end_turn() -> bool:
    hwnd = _civ5_hwnd()
    if not hwnd:
        return False
    _focus_civ5(hwnd)
    time.sleep(0.08)
    _key(VK_RETURN, up=False)
    _key(VK_RETURN, up=True)
    return True


def _inbox_click_point(hwnd: int) -> tuple[int, int]:
    rect = wintypes.RECT()
    _user32.GetClientRect(hwnd, ctypes.byref(rect))
    width = int(rect.right)
    # HostInbox is a full-width 28px strip at the top. Click the center so
    # paste does not land in the left TopPanel icons or the right chat box.
    x = max(8, width // 2) if width > 0 else INBOX_CLIENT_X
    return x, INBOX_CLIENT_Y


def _paste_line(hwnd: int, line: str) -> None:
    _set_clipboard(line)
    _focus_civ5(hwnd)
    time.sleep(0.05)
    click_x, click_y = _inbox_click_point(hwnd)
    _click_client(hwnd, click_x, click_y)
    time.sleep(0.08)
    _click_client(hwnd, click_x, click_y)
    time.sleep(0.08)
    _key(VK_CONTROL, up=False)
    _key(VK_V, up=False)
    time.sleep(0.04)
    _key(VK_V, up=True)
    _key(VK_CONTROL, up=True)
    # Do not send Enter. VK_RETURN after a missed inbox click hits the map
    # UI and can End Turn while production is still blocking (CP assert
    # ENDTURN_BLOCKING_PRODUCTION). HostInbox Poll reads the pasted line.
    # Click the map so the inbox EditBox is not still focused; otherwise
    # CONTROL_ENDTURN is rejected because the UI reports isFocused().
    width, height = _client_size(hwnd)
    _click_client(hwnd, max(80, width // 3), max(80, height // 2))


def inject_civ5_inbox_lines(lines: list[str]) -> bool:
    """Paste wire lines into the Civ5Ai InGame inbox. Host-only; apply still goes through SendCiv5AiCommands."""
    if not lines:
        return False
    if not _IS_WINDOWS or _user32 is None:
        log.warning("inbox inject: Win32 unavailable on this platform")
        return False
    deadline = time.monotonic() + 45.0
    hwnd = 0
    while time.monotonic() < deadline:
        hwnd = _civ5_hwnd()
        if hwnd:
            break
        time.sleep(0.25)
    if not hwnd:
        log.warning("inbox inject: Civilization V window not found")
        return False
    for line in lines:
        try:
            _paste_line(hwnd, line)
        except OSError as error:
            log.warning("inbox inject paste failed: %s", error)
            return False
        time.sleep(0.35)
    log.info("inbox inject: sent %d lines", len(lines))
    return True


def inject_apply_lines(lines: list[str]) -> bool:
    if not lines:
        return False
    # Dump already Arm()s the inbox. Paste the apply line only; Poll commits.
    ok = inject_civ5_inbox_lines(list(lines))
    if not ok:
        log.warning("inbox inject failed (%d lines)", len(lines))
    return ok


def inject_apply_payload(payload: str, session_id: str, player: int, turn: int) -> bool:
    if not payload:
        return False
    return inject_apply_lines(build_apply_lines(payload, session_id, player, turn))


def inject_from_player_dir(player_dir: Path, *, chat: bool = False) -> bool:
    from civ5_pending_apply import _player_context, load_apply_payload, load_chat_apply_payload

    context = _player_context(player_dir)
    if context is None:
        return False
    session_id, player, turn = context
    payload = load_chat_apply_payload(player_dir) if chat else load_apply_payload(player_dir)
    if payload is None:
        return False
    marker = player_dir / f"inbox_inject_turn_{turn}.done"
    lua_log: Path | None = None
    try:
        from civ5_lua_log_bridge import default_lua_log

        lua_log = default_lua_log()
    except Exception:
        pass
    if marker.is_file():
        return True
    try:
        marker.unlink()
    except OSError:
        pass
    if not inject_apply_payload(payload, session_id, player, turn):
        return False
    if lua_log is None or not lua_log.is_file():
        return False
    from civ5_pending_apply import wait_for_apply_confirmation

    confirmed = wait_for_apply_confirmation(lua_log, player, turn, timeout_seconds=60.0)
    if confirmed:
        marker.write_text(f"applied_at={time.strftime('%Y-%m-%dT%H:%M:%S')}\n", encoding="utf-8")
    return confirmed
