"""Inject Civ6Ai apply payloads into the hidden InGame inbox."""
from __future__ import annotations

import base64
import hashlib
import json
import logging
import os
import sys
import time
import uuid
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)

CHUNK_SIZE = 180
_QUEUE_STATE_NAME = "pending_apply_queue.json"


def civ6_mod_in_game_dirs() -> list[Path]:
    """Installed Civ6Ai mod InGame folders (where the game include()s PendingApply).

    Local Documents My Games is first (same rule as runtime I/O). OneDrive is a
    mirror only when that tree also has an installed copy. The repo copy is used
    when no installed mod exists (dev boxes/tests).
    """
    scripts = Path(__file__).resolve().parents[1]
    if str(scripts) not in sys.path:
        sys.path.insert(0, str(scripts))
    dirs: list[Path] = []
    try:
        from civ6_paths import preferred_my_games_root, installed_mod_dirs

        local = preferred_my_games_root() / "Mods" / "Civ6Ai" / "InGame"
        if local.is_dir():
            dirs.append(local)
        for mod in installed_mod_dirs():
            ingame = mod / "InGame"
            if ingame.is_dir():
                dirs.append(ingame)
    except Exception:
        home = Path.home()
        dirs.append(home / "Documents/My Games/Sid Meier's Civilization VI/Mods/Civ6Ai/InGame")
        dirs.append(home / "OneDrive/Documents/My Games/Sid Meier's Civilization VI/Mods/Civ6Ai/InGame")
        dirs = [d for d in dirs if d.is_dir()]
    if not dirs:
        repo = Path(__file__).resolve().parents[2]
        dirs.append(repo / "mod" / "Civ6Ai" / "InGame")
    seen: set[str] = set()
    unique: list[Path] = []
    for directory in dirs:
        try:
            key = str(directory.resolve())
        except OSError:
            key = str(directory)
        if key in seen:
            continue
        seen.add(key)
        unique.append(directory)
    unique.sort(key=lambda p: ( "onedrive" in str(p).replace("\\", "/").lower(), str(p).lower()))
    return unique


def _write_module(path: Path, content: str) -> bool:
    """Atomic write (tmp + replace) so the game never include()s a half-written file."""
    tmp = path.with_name(path.name + ".tmp")
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp.write_text(content, encoding="utf-8")
        for attempt in range(5):
            try:
                os.replace(tmp, path)
                return True
            except PermissionError:
                time.sleep(0.1 * (attempt + 1))
        os.replace(tmp, path)
        return True
    except OSError as error:
        log.warning("pending apply write failed %s: %s", path, error)
        return False


def pending_apply_id(payload: str, session_id: str, player: int, turn: int, kind: str = "turn") -> str:
    kind = "chat" if kind == "chat" else "turn"
    return hashlib.sha1(f"{session_id}|{int(player)}|{int(turn)}|{kind}|{payload}".encode("utf-8")).hexdigest()[:16]


def _queue_state_path() -> Path:
    """Host-side queue mirror so multi-seat publishes survive bridge restarts.

    Runtime I/O stays under local Documents My Games (never OneDrive).
    """
    scripts = Path(__file__).resolve().parents[1]
    if str(scripts) not in sys.path:
        sys.path.insert(0, str(scripts))
    try:
        from civ6_paths import preferred_my_games_root

        root = preferred_my_games_root() / "civ6ai"
        root.mkdir(parents=True, exist_ok=True)
        return root / _QUEUE_STATE_NAME
    except Exception:
        pass
    repo = Path(__file__).resolve().parents[2]
    runtime = repo / "runtime"
    runtime.mkdir(parents=True, exist_ok=True)
    return runtime / _QUEUE_STATE_NAME


def _load_queue_state() -> dict:
    path = _queue_state_path()
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError):
        return {}


def _save_queue_state(state: dict) -> None:
    path = _queue_state_path()
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(state, indent=2), encoding="utf-8")
    except OSError as error:
        log.warning("pending apply queue state save failed %s: %s", path, error)


def _escape_lua_string(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )


def _lua_queue_content(state: dict) -> str:
    lines = [
        "-- autogenerated by civ6ai host",
        "Civ6Ai_PendingApplyMeta = nil",
        'Civ6Ai_PendingApplyJson = ""',
        "Civ6Ai_PendingApplyQueue = {",
    ]
    for key in sorted(state.keys()):
        entry = state[key]
        if not isinstance(entry, dict):
            continue
        session_id = str(entry.get("session_id") or "")
        player = int(entry.get("player") or 0)
        turn = int(entry.get("turn") or 0)
        kind = str(entry.get("kind") or "turn")
        apply_id = str(entry.get("apply_id") or "")
        payload = str(entry.get("json") or "")
        lines.append(f'  ["{key}"] = {{')
        lines.append(f'    session_id = "{_escape_lua_string(session_id)}",')
        lines.append(f"    player = {player},")
        lines.append(f"    turn = {turn},")
        lines.append(f'    kind = "{_escape_lua_string(kind)}",')
        lines.append(f'    apply_id = "{_escape_lua_string(apply_id)}",')
        lines.append(f'    json = "{_escape_lua_string(payload)}",')
        lines.append("  },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def clear_pending_apply_lua() -> None:
    """Remove every host apply payload (new session / new game)."""
    _save_queue_state({})
    content = (
        "-- autogenerated by civ6ai host\n"
        "Civ6Ai_PendingApplyMeta = nil\n"
        'Civ6Ai_PendingApplyJson = ""\n'
        "Civ6Ai_PendingApplyQueue = nil\n"
    )
    for directory in civ6_mod_in_game_dirs():
        _write_module(directory / "Civ6Ai_PendingApply.lua", content)

def write_pending_apply_lua(
    payload: str,
    session_id: str,
    player: int,
    turn: int,
    *,
    kind: str = "turn",
    apply_id: str | None = None,
) -> int:
    """Write apply JSON into the PendingApply queue module; returns copies written.

    Retail InGame cannot read host disk files; include() only sees this registered
    module. Each entry carries session, player, turn, kind and a unique apply id so
    Lua applies it only for that seat and turn and only once (clearing Lua globals
    does not clear the file, and include() re-reads it). One entry per
    (player, kind), so seats never overwrite each other. Other sessions' entries are
    dropped.
    """
    if not payload:
        return 0
    kind = "chat" if kind == "chat" else "turn"
    key = f"{int(player)}:{kind}"
    apply_id = apply_id or pending_apply_id(payload, session_id, player, turn, kind)
    state = _load_queue_state()
    pruned: dict = {}
    for existing_key, entry in state.items():
        if not isinstance(entry, dict) or existing_key == key:
            continue
        if str(entry.get("session_id") or "") != str(session_id):
            continue
        try:
            entry_turn = int(entry.get("turn") or 0)
        except (TypeError, ValueError):
            continue
        if entry_turn < int(turn) - 2:
            continue
        pruned[existing_key] = entry
    pruned[key] = {
        "session_id": str(session_id),
        "player": int(player),
        "turn": int(turn),
        "kind": kind,
        "apply_id": apply_id,
        "json": payload,
    }
    _save_queue_state(pruned)
    content = _lua_queue_content(pruned)
    targets = civ6_mod_in_game_dirs()
    written = 0
    primary_ok = False
    scripts = Path(__file__).resolve().parents[1]
    if str(scripts) not in sys.path:
        sys.path.insert(0, str(scripts))
    try:
        from civ6_paths import is_onedrive_path
    except Exception:
        def is_onedrive_path(path: Path | str) -> bool:
            return "onedrive" in str(path).replace("\\", "/").lower()
    for directory in targets:
        path = directory / "Civ6Ai_PendingApply.lua"
        ok = _write_module(path, content)
        onedrive = is_onedrive_path(directory)
        if ok:
            written += 1
            if not onedrive:
                primary_ok = True
            log.info(
                "Wrote pending apply queue %s player=%s turn=%s kind=%s id=%s len=%d entries=%d",
                path, player, turn, kind, apply_id, len(payload), len(pruned),
            )
        elif onedrive:
            log.warning("pending apply OneDrive mirror skipped %s (local tree is primary)", path)
        else:
            log.warning("pending apply write failed %s", path)
    has_local = any(not is_onedrive_path(d) for d in targets)
    if has_local:
        return written if primary_ok else 0
    return written


_INJECT_UNAVAILABLE_LOGGED = False


def inbox_inject_enabled() -> bool:
    """Keystroke inbox inject is legacy/opt-in; the PendingApply module is the channel."""
    return os.environ.get("CIV6AI_INBOX_INJECT", "").strip() in {"1", "true", "yes"}


def build_apply_lines(
    payload: str,
    session_id: str,
    player: int,
    turn: int,
) -> list[str]:
    apply_id = uuid.uuid4().hex[:12]
    encoded = base64.b64encode(payload.encode("utf-8")).decode("ascii")
    chunks = [encoded[i : i + CHUNK_SIZE] for i in range(0, max(len(encoded), 1), CHUNK_SIZE)] or [""]
    lines = [
        f"CIV6AI|apply|begin|{apply_id}|{len(chunks)}|{player}|{turn}|{session_id}",
    ]
    for index, chunk in enumerate(chunks):
        lines.append(f"CIV6AI|apply|c|{apply_id}|{index}|{chunk}")
    lines.append(f"CIV6AI|apply|end|{apply_id}")
    return lines


def load_apply_payload(player_dir: Path) -> str | None:
    from civ6_pending_apply import load_apply_payload as _load

    return _load(player_dir)


def load_chat_apply_payload(player_dir: Path) -> str | None:
    from civ6_pending_apply import load_chat_apply_payload as _load

    return _load(player_dir)


def _apply_ready_marker(player: int, turn: int) -> str:
    return f"inbox|apply_ready|player={player}|turn={turn}|"


def _pending_apply_ok_marker(player: int) -> str:
    return f"bridge|pending_apply_ok|player={player}"


def _apply_payload_marker(player: int, turn: int) -> str:
    return f"bridge|apply_payload|player={player}|turn={turn}|"


def inject_confirmed(lua_log: Path | None, player: int, turn: int) -> bool:
    if lua_log is None or not lua_log.is_file():
        return False
    from civ6_startup_log import lua_log_tail_has_exact_marker, lua_log_tail_has_pattern

    if lua_log_tail_has_exact_marker(lua_log, _apply_ready_marker(player, turn)):
        return True
    if lua_log_tail_has_pattern(lua_log, _pending_apply_ok_marker(player)):
        return True
    return lua_log_tail_has_pattern(lua_log, _apply_payload_marker(player, turn))


def wait_for_inject_confirmation(
    lua_log: Path,
    player: int,
    turn: int,
    *,
    timeout_seconds: float = 30.0,
    start_offset: int | None = None,
) -> bool:
    from civ6_startup_log import wait_for_lua_log_exact_marker, wait_for_lua_log_pattern

    if wait_for_lua_log_exact_marker(
        lua_log,
        _apply_ready_marker(player, turn),
        timeout_seconds=timeout_seconds,
        check_tail_first=False,
        start_offset=start_offset,
    ):
        return True
    if wait_for_lua_log_pattern(
        lua_log,
        _pending_apply_ok_marker(player),
        timeout_seconds=timeout_seconds,
        check_tail_first=False,
        start_offset=start_offset,
    ):
        return True
    return wait_for_lua_log_pattern(
        lua_log,
        _apply_payload_marker(player, turn),
        timeout_seconds=timeout_seconds,
        check_tail_first=False,
        start_offset=start_offset,
    )


def inject_apply_lines(lines: list[str]) -> bool:
    global _INJECT_UNAVAILABLE_LOGGED
    try:
        from civ6_ui_automation import inject_inbox_lines
    except Exception as error:  # e.g. civ_mcp reference package not deployed
        if not _INJECT_UNAVAILABLE_LOGGED:
            _INJECT_UNAVAILABLE_LOGGED = True
            log.info("inbox inject unavailable (%s); using PendingApply module only", error)
        return False
    if not lines:
        return False
    arm_seconds = max(60, min(180, 30 + len(lines) * 2))
    lines = [f"CIV6AI|host|arm|{arm_seconds}"] + lines
    try:
        ok = inject_inbox_lines(lines)
    except Exception as error:
        if not _INJECT_UNAVAILABLE_LOGGED:
            _INJECT_UNAVAILABLE_LOGGED = True
            log.info("inbox inject unavailable (%s); using PendingApply module only", error)
        return False
    if not ok:
        log.warning("inbox inject failed (%d lines)", len(lines))
    return ok


def inject_apply_payload(payload: str, session_id: str, player: int, turn: int) -> bool:
    if not payload:
        return False
    lines = build_apply_lines(payload, session_id, player, turn)
    return inject_apply_lines(lines)


def inject_from_player_dir(player_dir: Path, *, chat: bool = False) -> bool:
    from civ6_pending_apply import _player_context

    context = _player_context(player_dir)
    if context is None:
        return False
    session_id, player, turn = context
    if chat:
        for snapshot_name in ("snapshot_chat.json", "snapshot.json"):
            snapshot_path = player_dir / snapshot_name
            if not snapshot_path.is_file():
                continue
            try:
                snapshot = json.loads(snapshot_path.read_text(encoding="utf-8-sig"))
                decision = snapshot.get("decision") if isinstance(snapshot, dict) else None
                if isinstance(decision, dict) and decision.get("turn") is not None:
                    turn = int(decision["turn"])
                    break
            except (OSError, json.JSONDecodeError, TypeError, ValueError):
                continue
        payload = load_chat_apply_payload(player_dir)
    else:
        payload = load_apply_payload(player_dir)
    if payload is None:
        return False
    marker = player_dir / f"inbox_inject_turn_{turn}.done"
    lua_log: Path | None = None
    try:
        from civ6_lua_log_bridge import default_lua_log

        lua_log = default_lua_log()
    except Exception:
        pass
    if marker.is_file() and inject_confirmed(lua_log, player, turn):
        return True
    try:
        marker.unlink()
    except OSError:
        pass
    confirm_offset = lua_log.stat().st_size if lua_log is not None and lua_log.is_file() else None
    if not inject_apply_payload(payload, session_id, player, turn):
        return False
    if lua_log is None or not lua_log.is_file():
        log.warning("Lua.log unavailable for inbox confirmation player=%s turn=%s", player, turn)
        return False
    wait_seconds = 60.0 if str(session_id).startswith("autotest-") else 25.0
    confirmed = wait_for_inject_confirmation(
        lua_log,
        player,
        turn,
        timeout_seconds=wait_seconds,
        start_offset=confirm_offset,
    )
    if not confirmed:
        log.warning("Inbox inject not confirmed player=%s turn=%s", player, turn)
        return False
    marker.write_text(f"applied_at={time.strftime('%Y-%m-%dT%H:%M:%S')}\n", encoding="utf-8")
    log.info("Inbox inject confirmed player=%s turn=%s", player, turn)
    return True
