"""Inject Civ6Ai apply payloads into the hidden InGame inbox."""
from __future__ import annotations

import base64
import logging
import time
import uuid
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)

CHUNK_SIZE = 180


def civ6_mod_in_game_dirs() -> list[Path]:
    """Live Civ6Ai mod InGame folders (for pending-apply Lua writes)."""
    repo = Path(__file__).resolve().parents[2]
    dirs: list[Path] = [repo / "mod" / "Civ6Ai" / "InGame", repo / "artifacts" / "Civ6Ai" / "InGame"]
    home = Path.home()
    for rel in (
        "OneDrive/Documents/My Games/Sid Meier's Civilization VI/Mods/Civ6Ai/InGame",
        "Documents/My Games/Sid Meier's Civilization VI/Mods/Civ6Ai/InGame",
    ):
        candidate = home / rel
        if candidate.is_dir():
            dirs.append(candidate)
    seen: set[str] = set()
    unique: list[Path] = []
    for directory in dirs:
        key = str(directory.resolve()) if directory.exists() else str(directory)
        if key in seen:
            continue
        seen.add(key)
        unique.append(directory)
    return unique


def clear_pending_apply_lua() -> None:
    """Remove stale host apply payload from mod Lua files."""
    content = (
        "-- autogenerated by civ6ai host\n"
        "Civ6Ai_PendingApplyMeta = nil\n"
        'Civ6Ai_PendingApplyJson = ""\n'
    )
    for directory in civ6_mod_in_game_dirs():
        path = directory / "Civ6Ai_PendingApply.lua"
        try:
            path.write_text(content, encoding="utf-8")
        except OSError as error:
            log.warning("pending apply clear failed %s: %s", path, error)


def write_pending_apply_lua(payload: str, session_id: str, turn: int) -> None:
    """Write apply JSON into the ImportFiles PendingApply module.

    Retail InGame cannot read host disk files. include() only sees this registered
    VFS module; a new filename per turn is invisible to the game. ``turn`` is
    logged for the host only — Lua uses Game.GetCurrentGameTurn().
    """
    if not payload:
        clear_pending_apply_lua()
        return
    escaped = payload.replace("\\", "\\\\").replace('"', '\\"')
    content = (
        "-- autogenerated by civ6ai host\n"
        f'Civ6Ai_PendingApplyMeta = {{ session_id = "{session_id}" }}\n'
        f'Civ6Ai_PendingApplyJson = "{escaped}"\n'
    )
    for directory in civ6_mod_in_game_dirs():
        path = directory / "Civ6Ai_PendingApply.lua"
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            log.info("Wrote pending apply lua %s turn=%s len=%d", path, turn, len(payload))
        except OSError as error:
            log.warning("pending apply write failed %s: %s", path, error)


def build_apply_lines(
    payload: str,
    session_id: str,
    player: int,
    turn: int,
) -> list[str]:
    apply_id = uuid.uuid4().hex[:12]
    encoded = base64.b64encode(payload.encode("utf-8")).decode("ascii")
    chunks = [encoded[i : i + CHUNK_SIZE] for i in range(0, max(len(encoded), 1), CHUNK_SIZE)] or [""]
    lines = [
        f"CIV6AI|apply|begin|{apply_id}|{len(chunks)}|{player}|{turn}|{session_id}",
    ]
    for index, chunk in enumerate(chunks):
        lines.append(f"CIV6AI|apply|c|{apply_id}|{index}|{chunk}")
    lines.append(f"CIV6AI|apply|end|{apply_id}")
    return lines


def load_apply_payload(player_dir: Path) -> str | None:
    from civ6_pending_apply import load_apply_payload as _load

    return _load(player_dir)


def load_chat_apply_payload(player_dir: Path) -> str | None:
    from civ6_pending_apply import load_chat_apply_payload as _load

    return _load(player_dir)


def _apply_ready_marker(player: int, turn: int) -> str:
    return f"inbox|apply_ready|player={player}|turn={turn}|"


def _pending_apply_ok_marker(player: int) -> str:
    return f"bridge|pending_apply_ok|player={player}"


def _apply_payload_marker(player: int, turn: int) -> str:
    return f"bridge|apply_payload|player={player}|turn={turn}|"


def inject_confirmed(lua_log: Path | None, player: int, turn: int) -> bool:
    if lua_log is None or not lua_log.is_file():
        return False
    from civ6_startup_log import lua_log_tail_has_exact_marker, lua_log_tail_has_pattern

    if lua_log_tail_has_exact_marker(lua_log, _apply_ready_marker(player, turn)):
        return True
    if lua_log_tail_has_pattern(lua_log, _pending_apply_ok_marker(player)):
        return True
    return lua_log_tail_has_pattern(lua_log, _apply_payload_marker(player, turn))


def wait_for_inject_confirmation(
    lua_log: Path,
    player: int,
    turn: int,
    *,
    timeout_seconds: float = 30.0,
    start_offset: int | None = None,
) -> bool:
    from civ6_startup_log import wait_for_lua_log_exact_marker, wait_for_lua_log_pattern

    if wait_for_lua_log_exact_marker(
        lua_log,
        _apply_ready_marker(player, turn),
        timeout_seconds=timeout_seconds,
        check_tail_first=False,
        start_offset=start_offset,
    ):
        return True
    if wait_for_lua_log_pattern(
        lua_log,
        _pending_apply_ok_marker(player),
        timeout_seconds=timeout_seconds,
        check_tail_first=False,
        start_offset=start_offset,
    ):
        return True
    return wait_for_lua_log_pattern(
        lua_log,
        _apply_payload_marker(player, turn),
        timeout_seconds=timeout_seconds,
        check_tail_first=False,
        start_offset=start_offset,
    )


def inject_apply_lines(lines: list[str]) -> bool:
    from civ6_ui_automation import inject_inbox_lines

    if not lines:
        return False
    arm_seconds = max(60, min(180, 30 + len(lines) * 2))
    lines = [f"CIV6AI|host|arm|{arm_seconds}"] + lines
    ok = inject_inbox_lines(lines)
    if not ok:
        log.warning("inbox inject failed (%d lines)", len(lines))
    return ok


def inject_apply_payload(payload: str, session_id: str, player: int, turn: int) -> bool:
    if not payload:
        return False
    lines = build_apply_lines(payload, session_id, player, turn)
    return inject_apply_lines(lines)


def inject_from_player_dir(player_dir: Path, *, chat: bool = False) -> bool:
    from civ6_pending_apply import _player_context

    context = _player_context(player_dir)
    if context is None:
        return False
    session_id, player, turn = context
    if chat:
        for snapshot_name in ("snapshot_chat.json", "snapshot.json"):
            snapshot_path = player_dir / snapshot_name
            if not snapshot_path.is_file():
                continue
            try:
                import json

                snapshot = json.loads(snapshot_path.read_text(encoding="utf-8-sig"))
                decision = snapshot.get("decision") if isinstance(snapshot, dict) else None
                if isinstance(decision, dict) and decision.get("turn") is not None:
                    turn = int(decision["turn"])
                    break
            except (OSError, json.JSONDecodeError, TypeError, ValueError):
                continue
        payload = load_chat_apply_payload(player_dir)
    else:
        payload = load_apply_payload(player_dir)
    if payload is None:
        return False
    marker = player_dir / f"inbox_inject_turn_{turn}.done"
    lua_log: Path | None = None
    try:
        from civ6_lua_log_bridge import default_lua_log

        lua_log = default_lua_log()
    except Exception:
        pass
    if marker.is_file() and inject_confirmed(lua_log, player, turn):
        return True
    try:
        marker.unlink()
    except OSError:
        pass
    confirm_offset = lua_log.stat().st_size if lua_log is not None and lua_log.is_file() else None
    if not inject_apply_payload(payload, session_id, player, turn):
        return False
    if lua_log is None or not lua_log.is_file():
        log.warning("Lua.log unavailable for inbox confirmation player=%s turn=%s", player, turn)
        return False
    wait_seconds = 60.0 if str(session_id).startswith("autotest-") else 25.0
    confirmed = wait_for_inject_confirmation(
        lua_log,
        player,
        turn,
        timeout_seconds=wait_seconds,
        start_offset=confirm_offset,
    )
    if not confirmed:
        log.warning("Inbox inject not confirmed player=%s turn=%s", player, turn)
        return False
    marker.write_text(f"applied_at={time.strftime('%Y-%m-%dT%H:%M:%S')}\n", encoding="utf-8")
    log.info("Inbox inject confirmed player=%s turn=%s", player, turn)
    return True
