# Sync Civ5Ai mod into Civilization V MODS folder and generate paths.
param(
    [string]$RepoRoot = "",
    [string]$Python = "",
    [int]$SidecarTimeout = 120,
    [switch]$Autotest,
    [int]$AutotestStopTurn = 3,
    [string]$ManagedSeats = "0",
    [string]$SessionId = "",
    [switch]$SidecarLive,
    [switch]$FastEndTurn,
    [switch]$InstallInGameHooks
)

$ErrorActionPreference = "Stop"

$AutotestFlag = if ($Autotest) { 1 } else { 0 }
$SidecarLiveFlag = if ($SidecarLive) { 1 } else { 0 }
$FastEndTurnFlag = if ($FastEndTurn) { 1 } else { 0 }

$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $ScriptRoot "Civ5Ai-EnvProfile.ps1")

$Repo = if ($RepoRoot) { $RepoRoot } else { Get-Civ5AiRepoRoot -FromScriptRoot $ScriptRoot }
$SourceMod = Join-Path $Repo "artifacts\Civ5Ai"
$primaryPaths = Get-Civ5AiPaths
$canonicalCiv5AiRoot = $primaryPaths.Civ5AiRoot
$myGamesRoots = Get-Civ5AiMyGamesRoots
if (-not $SessionId) { $SessionId = New-Civ5AiSessionId }

if (-not $Python) {
    $Python = (Resolve-Civ5AiPython)
}

if ($Autotest) {
    Write-Civ5AiAutotestEnv -StopTurn $AutotestStopTurn -ManagedSeats $ManagedSeats -Civ5AiRoot $canonicalCiv5AiRoot -SidecarLive $SidecarLiveFlag -FastEndTurn $FastEndTurnFlag -SessionId $SessionId
    Write-Civ5AiRuntimeJson -Civ5AiRoot $canonicalCiv5AiRoot -SessionId $SessionId -Python $Python -Repo $Repo -SidecarLive $SidecarLiveFlag -SidecarTimeoutSeconds $SidecarTimeout
}

function Install-Civ5AiModToRoot {
    param(
        [string]$MyGamesRoot,
        [string]$PythonExe,
        [string]$RepoPath,
        [int]$Timeout,
        [int]$AutotestFlag,
        [int]$LiveFlag,
        [int]$FastFlag,
        [int]$StopTurn,
        [string]$Seats
    )
    $modRoot = Join-Path $MyGamesRoot "MODS\Civ5Ai"
    Write-Host ('Syncing Civ5Ai mod to ' + $modRoot)
    New-Item -ItemType Directory -Force -Path $modRoot | Out-Null
    $luaDest = Join-Path $modRoot "Lua"
    if (Test-Path -LiteralPath $luaDest) {
        Remove-Item -LiteralPath $luaDest -Recurse -Force
    }
    Copy-Item -Recurse -Force (Join-Path $SourceMod "Lua") $luaDest
    Copy-Item -Force (Join-Path $SourceMod "Civ5Ai.modinfo") (Join-Path $modRoot "Civ5Ai.modinfo")
    New-Item -ItemType Directory -Force -Path (Join-Path $modRoot "runtime") | Out-Null
    $stalePending = Join-Path $modRoot "Lua\Civ5Ai_PendingApply.lua"
    if (Test-Path -LiteralPath $stalePending) {
        Remove-Item -LiteralPath $stalePending -Force
        Write-Host ('Removed stale mod VFS pending apply: ' + $stalePending)
    }

    $rootFwd = $canonicalCiv5AiRoot.Replace('\', '/')
    $repoFwd = $RepoPath.Replace('\', '/')
    $pyFwd = $PythonExe.Replace('\', '/')
    $logFwd = ([IO.Path]::GetDirectoryName($primaryPaths.LuaLog)).Replace('\', '/')
    $applyPending = (Join-Path $canonicalCiv5AiRoot "apply_pending.lua").Replace('\', '/')
    $applyPendingBlock = "  ApplyPendingPaths = {`n    `"$applyPending`",`n  },"
    $pathsLua = Join-Path $modRoot "Lua\Civ5Ai_Paths.lua"
    $pathsContent = @"
-- Generated by Invoke-Civ5AiModSync.ps1
Civ5Ai_Paths = {
  Python = "$pyFwd",
  Repo = "$repoFwd",
  Civ5AiRoot = "$rootFwd",
  LogDir = "$logFwd",
  SidecarTimeoutSeconds = $Timeout,
  SidecarScript = "sidecar/run_civ5.py",
  Autotest = $AutotestFlag,
  SidecarLive = $LiveFlag,
  FastEndTurn = $FastFlag,
  AutotestStopTurn = $StopTurn,
  ManagedSeats = "$Seats",
  SessionId = "$SessionId",
$applyPendingBlock
}
"@
    Write-Utf8NoBom -Path $pathsLua -Content $pathsContent

    New-Item -ItemType Directory -Force -Path $canonicalCiv5AiRoot | Out-Null
    if ($SessionId) {
        Ensure-Civ5AiSessionLayout -Civ5AiRoot $canonicalCiv5AiRoot -SessionId $SessionId -ManagedSeats $Seats
    }
    return $modRoot
}

$installed = @()
foreach ($root in $myGamesRoots) {
    $installed += Install-Civ5AiModToRoot `
        -MyGamesRoot $root `
        -PythonExe $Python `
        -RepoPath $Repo `
        -Timeout $SidecarTimeout `
        -AutotestFlag $AutotestFlag `
        -LiveFlag $SidecarLiveFlag `
        -FastFlag $FastEndTurnFlag `
        -StopTurn $AutotestStopTurn `
        -Seats $ManagedSeats
}

$hostEnvExample = Join-Path $Repo "fixtures\civ5\host.env.example"
$hostEnvTarget = Join-Path $primaryPaths.Civ5AiRoot "host.env"
if (-not (Test-Path -LiteralPath $hostEnvTarget)) {
    Copy-Item -LiteralPath $hostEnvExample -Destination $hostEnvTarget
    Write-Host ('Created ' + $hostEnvTarget + ' - add API keys before live runs.')
}

if ($InstallInGameHooks) {
    $installRoot = Find-Civ5InstallRoot
    if ($installRoot) {
        Install-Civ5AiInGameHooks -RepoRoot $Repo -Civ5Install $installRoot -MyGamesRoot $primaryPaths.MyGames
    } else {
        Write-Host "InstallInGameHooks: Civ5 install not found; skipped Expansion2 hook."
    }
}

Write-Host 'Done. For -Automation, use -InstallInGameHooks. For normal play, enable Civ5Ai under Mod Browser.'
