# Sync Civ6Ai Workshop mod into Civilization VI Mods folder and generate paths.
param(
    [string]$Civ6ModsRoot = "",
    [string]$Python = "",
    [string]$RepoRoot = "",
    [int]$SidecarTimeout = 120,
    [switch]$SeatExperiment,
    [switch]$Autotest,
    [int]$AutotestStopTurn = 20,
    [string]$ManagedSeats = "0,1,2,3,4",
    [string]$SessionId = "",
    [switch]$SidecarLive,
    [switch]$FastEndTurn,
    [switch]$RefreshModDatabase
)

$ErrorActionPreference = "Stop"

$SeatExperimentFlag = if ($SeatExperiment) { 1 } else { 0 }
$AutotestFlag = if ($Autotest) { 1 } else { 0 }
$SidecarLiveFlag = if ($SidecarLive) { 1 } else { 0 }
$FastEndTurnFlag = if ($FastEndTurn) { 1 } else { 0 }

$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $ScriptRoot "Civ6Ai-EnvProfile.ps1")

$Repo = if ($RepoRoot) { $RepoRoot } else { Get-Civ6AiRepoRoot -FromScriptRoot $ScriptRoot }
$SourceMod = Join-Path $Repo "artifacts\Civ6Ai"
$primaryPaths = Get-Civ6AiPaths
$canonicalCiv6AiRoot = $primaryPaths.Civ6AiRoot
$myGamesRoots = Get-Civ6AiMyGamesRoots
if (-not $SessionId) { $SessionId = New-Civ6AiSessionId }

if (-not $Python) {
    $Python = (Resolve-Civ6AiPython)
}

if ($Autotest) {
    Write-Civ6AiAutotestEnv -StopTurn $AutotestStopTurn -ManagedSeats $ManagedSeats -Civ6AiRoot $canonicalCiv6AiRoot -SidecarLive $SidecarLiveFlag -FastEndTurn $FastEndTurnFlag -SessionId $SessionId
}

function Install-Civ6AiModToRoot {
    param(
        [string]$MyGamesRoot,
        [string]$PythonExe,
        [string]$RepoPath,
        [int]$Timeout,
        [int]$SeatFlag,
        [int]$AutotestFlag,
        [int]$LiveFlag,
        [int]$FastFlag,
        [int]$StopTurn,
        [string]$Seats
    )
    $modRoot = Join-Path $MyGamesRoot "Mods\Civ6Ai"
    Write-Host ('Syncing Civ6Ai mod to ' + $modRoot)
    if (Test-Path -LiteralPath $modRoot) {
        Remove-Item -LiteralPath $modRoot -Recurse -Force
    }
    New-Item -ItemType Directory -Force -Path $modRoot | Out-Null
    Copy-Item -Recurse -Force (Join-Path $SourceMod "*") $modRoot

    $rootFwd = $canonicalCiv6AiRoot.Replace('\', '/')
    $repoFwd = $RepoPath.Replace('\', '/')
    $pyFwd = $PythonExe.Replace('\', '/')
    $logFwd = ([IO.Path]::GetDirectoryName($primaryPaths.LuaLog)).Replace('\', '/')
    $pathsLua = Join-Path $modRoot "InGame\Civ6Ai_Paths.lua"
    $pathsContent = @"
-- Generated by Invoke-Civ6AiModSync.ps1
Civ6Ai_Paths = {
  Python = "$pyFwd",
  Repo = "$repoFwd",
  Civ6AiRoot = "$rootFwd",
  LogDir = "$logFwd",
  SidecarTimeoutSeconds = $Timeout,
  SidecarScript = "sidecar/run_civ6.py",
  SeatExperiment = $SeatFlag,
  Autotest = $AutotestFlag,
  SidecarLive = $LiveFlag,
  FastEndTurn = $FastFlag,
  AutotestStopTurn = $StopTurn,
  ManagedSeats = "$Seats",
  SessionId = "$SessionId",
  EnableSinglePlayerChat = 1,
}
"@
    Write-Utf8NoBom -Path $pathsLua -Content $pathsContent

    $pendingLua = Join-Path $modRoot "InGame\Civ6Ai_PendingApply.lua"
    Write-Utf8NoBom -Path $pendingLua -Content @"
-- Generated by Invoke-Civ6AiModSync.ps1
Civ6Ai_PendingApplyMeta = nil
Civ6Ai_PendingApplyJson = ""
"@

    $runtimeLua = Join-Path $modRoot "Gameplay\Civ6Ai_Runtime.lua"
    $runtimeContent = @"
-- Generated by Invoke-Civ6AiModSync.ps1
Civ6Ai_Runtime = {
  Root = "$rootFwd",
  Repo = "$repoFwd",
  Python = "$pyFwd",
  LogDir = "$logFwd",
  Autotest = $AutotestFlag,
  SidecarLive = $LiveFlag,
  FastEndTurn = $FastFlag,
  AutotestStopTurn = $StopTurn,
  ManagedSeats = "$Seats",
  SessionId = "$SessionId",
  SidecarTimeoutSeconds = $Timeout,
}
"@
    Write-Utf8NoBom -Path $runtimeLua -Content $runtimeContent

    New-Item -ItemType Directory -Force -Path $canonicalCiv6AiRoot | Out-Null
    if ($SessionId) {
        Ensure-Civ6AiSessionLayout -Civ6AiRoot $canonicalCiv6AiRoot -SessionId $SessionId -ManagedSeats $Seats
    }
    if ($RefreshModDatabase) {
        Reset-Civ6ModDatabase -MyGamesRoot $MyGamesRoot
    }
    return $modRoot
}

$installed = @()
foreach ($root in $myGamesRoots) {
    $installed += Install-Civ6AiModToRoot `
        -MyGamesRoot $root `
        -PythonExe $Python `
        -RepoPath $Repo `
        -Timeout $SidecarTimeout `
        -SeatFlag $SeatExperimentFlag `
        -AutotestFlag $AutotestFlag `
        -LiveFlag $SidecarLiveFlag `
        -FastFlag $FastEndTurnFlag `
        -StopTurn $AutotestStopTurn `
        -Seats $ManagedSeats
}

if ($Civ6ModsRoot) {
    $target = $Civ6ModsRoot
    if (-not ($installed -contains $target)) {
        $parent = Split-Path -Parent $target
        Install-Civ6AiModToRoot `
            -MyGamesRoot $parent `
            -PythonExe $Python `
            -RepoPath $Repo `
            -Timeout $SidecarTimeout `
            -SeatFlag $SeatExperimentFlag `
            -AutotestFlag $AutotestFlag `
            -LiveFlag $SidecarLiveFlag `
            -FastFlag $FastEndTurnFlag `
            -StopTurn $AutotestStopTurn `
            -Seats $ManagedSeats | Out-Null
    }
}

$hostEnvExample = Join-Path $Repo "fixtures\civ6\host.env.example"
$hostEnvTarget = Join-Path $primaryPaths.Civ6AiRoot "host.env"
if (-not (Test-Path -LiteralPath $hostEnvTarget)) {
    Copy-Item -LiteralPath $hostEnvExample -Destination $hostEnvTarget
    Write-Host ('Created ' + $hostEnvTarget + ' - add API keys before live runs.')
}

Write-Host 'Done. Restart Civ6, then enable Civ6Ai under Additional Content -> Installed.'
